export const  users = [
    {
      id : 1,
      nombres: "Juan Pérez",
      inicial: "JP",
      color : 'bg-red-500',
      costo: "3390",
      producto: "Combustible",
      tamaño: "2mb",
      tiempo: "10 minutos",
    },
    {
      id : 2,
      nombres: "María Rodríguez",
      inicial: "MR",
      color : 'bg-orange-500',
      costo: "1750",
      producto: "Batería",
      tamaño: "2mb",
      tiempo: "18 minutos",
    },
    {
      id : 3,
      nombres: "Carlos Gómez",
      inicial: "CG",
      color : 'bg-amber-400',
      costo: "7650",
      producto: "refrigerante",
      tamaño: "2mb",
      tiempo: "10 minutos",
      
    },
    {
      id : 4,
      nombres: "Laura Martínez",
      inicial: "LM",
      color : 'bg-lime-500',
      costo: "1350",
      producto: "Discos de freno",
      tamaño: "2mb",
      tiempo: "10 minutos",
    },
    {
      id : 5,
      nombres: "Andrés López",
      inicial: "AL",
      color : 'bg-green-500',
      costo: "6550",
      producto: " Aceite",
      tamaño: "2mb",
      tiempo: "42 minutos",
    },
    {
      id : 6,
      nombres: "Ana Fernández",
      inicial: "AF",
      color : 'bg-teal-500',
      costo: "1450",
      producto: "Filtro de aire",
      tamaño: "2mb",
      tiempo: "10 minutos",
    },
    {
      id : 7,
      nombres: "Roberto Sánchez",
      inicial: "RS",
      color : 'bg-sky-600',
      costo: "3120",
      producto: " Filtro de aceite",
      tamaño: "2mb",
      tiempo: "5  horas ",
    },
    {
      id : 8,
      nombres: "Marta Torres",
      inicial: "MT",
      color : 'bg-indigo-700',
      costo: "3350",
      producto: "Filtro de combustible",
      tamaño: "2mb",
      tiempo: "10 minutos",
    },
    {
      id : 9,
      nombres: "Javier Ramírez",
      inicial: "JR",
      color : 'bg-violet-700',
      costo: "3950",
      producto: "Filtro de habitáculo",
      tamaño: "2mb",
      tiempo: "3 horas",
    },
    {
      id : 10,
      nombres: "Silvia Díaz",
      inicial: "SD",
      color : 'bg-pink-500',
      costo: "3750",
      producto: "freno de disco",
      tamaño: "2mb",
      tiempo: "50 minutos",
    },
    {
      id : 11,
      nombres: "Eduardo Vargas",
      inicial: "EV",
      color : 'bg-teal-900',
      costo: "350",
      producto: "Filtro de partículas",
      tamaño: "2mb",
      tiempo: "2 horas",
      
    },
    {
      id : 12,
      nombres: "Paola Castro",
      inicial: "PC",
      color : 'bg-blue-950',
      costo: "2350",
      producto: "Filtro de polen",
      tamaño: "2mb",
      tiempo: "30 minutos",
    }
  ];